### ISSUE TITLE
Unable to refresh users list

### ISSUE THREAD

**Issue by peppoonline** [zSeriesGuy/Tautulli#7] opened 2019-04-07 05:41 UTC
Hello,

I'm at the newest branch (3.0.00 and commit) and I get this error messages:

19-04-07 07:37:58 - WARNING :: CP Server Thread-12 : Failed to access uri endpoint /api/servers/c705664cd78e63d4759560143ad35a5fa898c2cf/shared_servers. Status code 404
2019-04-07 07:37:58 - WARNING :: CP Server Thread-12 : Tautulli PlexTV :: Plex-Privat: Unable to parse shared server list XML for get_full_users_list: 'NoneType' object has no attribute 'getElementsByTagName'.
2019-04-07 07:37:58 - WARNING :: CP Server Thread-12 : Tautulli Users :: Unable to refresh users list.

Everything is working now, after I switched to port 32400 without SSL - which I don't understand, but no problem. BUT it can't get all my users...so most of them are displayed as "LOCAL".
Where can I try to search for this problem? :)

Greeting

**Comment by peppoonline** [comment] 2019-04-07 06:05
After I installed an older version of the Tautulli master branch, did the initial config and the updated to your branch, everything works now...sorry for the issue.

**Comment by zSeriesGuy** [comment] 2019-04-07 11:05
@peppoonline Was your first install of 3.0.0 a new install, not an upgrade?
Was your plex server set up to require SSL?
I'll see if I can recreate this.
Thanks for reporting this.

**Comment by peppoonline** [comment] 2019-04-07 19:48
Hey, it was a fresh install, yeah... after I tried an upgrade, it worked (it had the users synced then...)
Mhhh don't know if it was a requirement - I had the SSL argument "under custom access URLS" (https://xxx:443). But I also tried it without it.

Still getting this in the logs:

  File "C:\Admin\Tautulli-master\plexpy\logger.py", line 341, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Admin\Tautulli-master\plexpy\servers.py", line 149, in refresh_users
    result = users.refresh_users()
  File "C:\Admin\Tautulli-master\plexpy\users.py", line 54, in refresh_users
    shared_libraries = user.pop('shared_libraries')
KeyError: 'shared_libraries'

It's a win2016 install though.

**Comment by quietlifeproductions** [comment] 2019-04-14 20:27
Hi, I'm struggling with new users not appearing on the list with the refresh users function not working either. Mine's a Ubuntu install, tried selecting/deselecting SSL on the server list but no help. Additionally, whenever either new (unlisted) user is streaming it causes an error which disconnects the server monitoring, I assume this is a conflict as the user technically doesn't exist.

Can you possibly post details of how I would resolve this? I have an official version of Tautulli running on another server, can I replace files from that into this install perhaps?

Thanks, I'm a little out of my depth with this as is probably glaringly apparent!

**Comment by zSeriesGuy** [comment] 2019-04-14 23:34
@quietlifeproductions Was this a new install? Do you have the tautulli log available from when you first started it up?
I have tried recreating this issue and have not been successful. It works for me.
If you don't have the log, shut down tautulli, delete the config.ini and tautulli.db files, and empty out the logs folder. Start up tautulli and send me the log.

Please post a link to your complete Tautulli logs on Gist.
How to Find Your Logs
View the Tautulli logs by clicking on "View Logs" in the settings menu. Click the "Download logs" button to save a copy of the log file. If Tautulli is unable to start, then the tautulli.log file is located in the logs folder where Tautulli is installed. Paste the logs on Gist and post the link here, do not upload the file as an attachment.

**Comment by quietlifeproductions** [comment] 2019-04-15 10:59
Thanks for the prompt reply. I've never done this before so hope I've followed the correct steps:

https://gist.github.com/quietlifeproductions/e225a0642a1d5857642c62d08f3ea8de

Many thanks for your help.

QL

**Comment by zSeriesGuy** [comment] 2019-04-15 11:40
@quietlifeproductions Got it. Thanks.

That's odd. Right after the webserver is initialized, you are getting a signal 15 which I believe is a sigterm to terminate tautulli. This occurred a couple of times. Any idea where that might be coming from?

When you installed tautulli, did you follow the instructions in the installation guide starting at the optional steps to set up the tautulli user and set the file ownership?
https://github.com/Tautulli/Tautulli-Wiki/wiki/Installation#linux
I don't know if that would have anything to do with it since I don't see anything in your log dealing with file permissions. Just trying to step thru this to figure out what is going on.

Are you starting tautulli using the command python Tautulli.py? If so, are you doing anything in the terminal window before accessing the webserver? Or are you starting it as a daemon?

**Comment by zSeriesGuy** [comment] 2019-04-15 11:56
@quietlifeproductions Looking thru the log again, It appears that the third start is after you deleted the config.ini and tautulli.db and started fresh. It discovered your two servers. But crashed on the refresh_users, as you previously mentioned.
The error would indicate that the a user was defined that did not have any shared libraries. Is that true?
All of my users have shared libraries. Perhaps that is what I was missing in my testing. Let me know if you have users defined that have no shared libraries.

**Comment by zSeriesGuy** [comment] 2019-04-15 12:02
@quietlifeproductions Yep. That is what the issue is. A user defined with no shared libraries. I was able to recreate this issue. 
I will fix it this evening.
Thanks.

**Comment by quietlifeproductions** [comment] 2019-04-15 12:04
Thank you, I've installed Tautulli as a daemon on root so assumed permissions would not be an issue.

Practically none of my users have shared libraries (shared we me that is). The ratio is actually 1 in 14 shares libraries back with me. If you meant the other way around, I share libraries with 13 out of the 14 users that I'm expecting to see in the users list. (Only 12 are visible, hence the issue I've logged).

**Comment by quietlifeproductions** [comment] 2019-04-15 12:11
That's amazing, thank you!

**Comment by zSeriesGuy** [comment] 2019-04-15 21:15
@quietlifeproductions @peppoonline 
This issue should now be resolved. Sorry about that.
Download the updated code and give it a go.
Let me know if results are better.
Thank you.

**Comment by quietlifeproductions** [comment] 2019-04-16 19:12
I cannot thank you enough, that has worked like a charm!

Really appreciate the effort, and the speed in which you've responded. Many, many thanks.

**Comment by zSeriesGuy** [comment] 2019-04-16 21:44
@quietlifeproductions You are welcome. I hope you like what this version of Tautulli does.
It is a shame that the Tautulli owner won't merge my code due to the complexity and quantity of the changes. Oh well.
Because this code most likely will never get merged, please understand that there is no official Tautulli support for this code base. And you will not be able to fall back to the official version.
But please don't let that stop you from trying and using the code. 
If you find any more bugs, please open an issue.

**Closed as completed by zSeriesGuy** 2019-04-16 21:44 UTC
